name: spacescape
description: A 2D top down space shooter.

publish_to: "none"

version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flame: 1.3.0
  flame_audio: 1.3.1
  provider: 6.0.3
  flutter_carousel_slider: 1.0.9
  hive: 2.2.3
  hive_generator: 1.1.3
  path_provider: 2.0.11
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  hive_flutter: ^1.1.0

dev_dependencies:
  build_runner: 2.2.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
  fonts:
    - family: BungeeInline
      fonts:
        - asset: assets/fonts/BungeeInline/BungeeInline-Regular.ttf
